name: chronos
author: dkharms
description: |
  chronos provides functionality for storing benchmark results,
  emitting comparisons of benchmark measurements across git commits
  and visualizing results on your personal GitHub Pages deployment

inputs:
  github_token:
    description: |
      Your GitHub token
    required: true
  benchmarks_file_path:
    description: |
      Path to benchmark results of your current workflow run
    required: true
  branch_storage:
    description: |
      This git branch will be used as a storage for benchmarks
      measurements across all executions with `store` action
    default: chronos-storage
  branch_github_pages:
    description: |
      This git branch will be used as a storage for benchmarks
      measurements across all executions with `store` action
    default: gh-pages
  action_to_perform:
    description: |
      You can perform `store` and/or `summarize` action.
      - `store` action stores benchmark results in `branch-storage` git branch
      - `summarize` action compares measurements from current run with previous one and adds job summary
    required: true

runs:
  using: composite
  steps:
  - name: Setup Golang
    uses: actions/setup-go@v5
    with:
      go-version: '1.25'
      cache: true

  - name: Build binary
    shell: bash
    run: go build -o chronos cmd/chronos/main.go

  - name: Run binary
    shell: bash
    run: ./chronos
    env:
      INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
      INPUT_BENCHMARKS_FILE_PATH: ${{ inputs.benchmarks_file_path }}
      INPUT_BRANCH_STORAGE: ${{ inputs.branch_storage }}
      INPUT_BRANCH_GITHUB_PAGES: ${{ inputs.branch_github_pages }}
      INPUT_ACTION_TO_PERFORM: ${{ inputs.action_to_perform }}
