name: chronosbnch
author: dkharms
description: |
  chronos provides functionality for Continuous Benchmarks

inputs:
  language-tool:
    description: |
      Tool's name which will be used for parsing benchmark results.
      For now only `gotool` is supported.
    required: true
  github-token:
    description: |
      Your GitHub token
    required: true
  branch-storage:
    description: |
      This git branch will be used as a storage for benchmarks
      measurements across all executions with `store` action
    default: chronos-storage
  benchmarks-file-path:
    description: |
      Path to benchmark results of your current workflow run
  action-to-perform:
    description: |
      You can perform `save`, `summarize` or `publish` action:
      - `save` action stores benchmark results in `branch-storage` git branch;
      - `summarize` action compares measurements from current run with previous one and adds job summary;
      - `publish` action fetches recent benchmark results from `branch-storage` git branch and publishes them to GitHub pages;
    required: true

runs:
  using: composite
  steps:
  - name: Setup Golang
    uses: actions/setup-go@v5
    with:
      go-version: '1.25'
      cache: false

  - name: Build binary
    shell: bash
    working-directory: ${{ github.action_path }}
    run: go build -o chronos cmd/chronos/main.go

  - name: Run binary
    shell: bash
    working-directory: ${{ github.action_path }}
    run: ./chronos
    env:
      INPUT_GITHUB-TOKEN: ${{ inputs.github-token }}
      INPUT_BRANCH-STORAGE: ${{ inputs.branch-storage }}
      INPUT_BENCHMARKS-FILE-PATH: ${{ inputs.benchmarks-file-path }}
      INPUT_ACTION-TO-PERFORM: ${{ inputs.action-to-perform }}
