name: chronos
author: dkharms
description: |
  chronos provides functionality for storing benchmark results,
  emitting comparisons of benchmark measurements across git commits
  and visualizing results on your personal GitHub Pages deployment

inputs:
  github-token:
    description: |
      Your GitHub token
    required: true
  benchmarks-file-path:
    description: |
      Path to benchmark results of your current workflow run
  branch-storage:
    description: |
      This git branch will be used as a storage for benchmarks
      measurements across all executions with `store` action
    default: chronos-storage
  branch-github-pages:
    description: |
      This git branch will be used as a storage for benchmarks
      measurements across all executions with `store` action
    default: gh-pages
  action-to-perform:
    description: |
      You can perform `save`, `summarize` or `publish` action:
      - `save` action stores benchmark results in `branch-storage` git branch;
      - `summarize` action compares measurements from current run with previous one and adds job summary;
      - `publish` action fetches recent benchmark results from `branch-storage` git branch and publishes them to GitHub pages;
    required: true

runs:
  using: composite
  steps:
  - name: Setup Golang
    uses: actions/setup-go@v5
    with:
      go-version: '1.25'
      cache: true

  - name: Build binary
    shell: bash
    run: go build -o chronos cmd/chronos/main.go

  - name: Run binary
    shell: bash
    run: ./chronos
    env:
      INPUT_GITHUB-TOKEN: ${{ inputs.github-token }}
      INPUT_BENCHMARKS-FILE-PATH: ${{ inputs.benchmarks-file-path }}
      INPUT_BRANCH-STORAGE: ${{ inputs.branch-storage }}
      INPUT_BRANCH-GITHUB-PAGES: ${{ inputs.branch-github-pages }}
      INPUT_ACTION-TO-PERFORM: ${{ inputs.action-to-perform }}
