on: [push]

permissions:
  contents: write
  deployments: write
  pull-requests: write

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v5
      - id: foo
        uses: dkharms/chronos@e1be5273417ce01ab023d5e9eddfac3ee51f5e87
        with:
          github_token: ${{ github.token }}
          benchmarks_file_path: output.txt
          action_to_perform: store
