on: [push]

permissions:
  contents: write
  deployments: write
  pull-requests: write

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v5
      - id: foo
        uses: dkharms/chronos@d18c6f4b9f53e3b35a0f2679d5ccfe89a15e181f
        with:
          github-token: ${{ github.token }}
          benchmarks-file-path: output.txt
          action-to-perform: store
