on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v5
      - id: foo
        uses: dkharms/chronos@56c863adc89708d4d769caf4a1007b4df6c78b37
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          benchmarks-file-path: output.txt
          action-to-perform: store
