on: [push]

permissions:
  contents: write
  deployments: write
  pull-requests: write

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v5
      - id: foo
        uses: dkharms/chronos@10e279162b1aa73ffe3aa3335ac2d97e4bfcc614
        with:
          github-token: ${{ github.token }}
          benchmarks-file-path: output.txt
          action-to-perform: store
