on: [push]

permissions:
  contents: write
  deployments: write
  pull-requests: write

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v5
      - id: foo
        uses: dkharms/chronos@9ffdb7fde3e958d897a71217f50ad50bcc2eb019
        with:
          github_token: ${{ github.token }}
          benchmarks_file_path: output.txt
          action_to_perform: store
