name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-test:
    runs-on: ubuntu-latest
    name: Run Linter and Tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true

      - name: Run Linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5

      - name: Run Golang Test
        shell: bash
        run: go test -count=1 ./...
